#!/usr/bin/env bash

if [[ -n "$HYPRLAND_INSTANCE_SIGNATURE" ]]; then
    SESSION_TYPE="hyprland"
else
    SESSION_TYPE="steamos"
fi

NVAPI_STATUS=0
MANGOHUD_TYPE=0
GAMESCOPE=0
WAYLAND=1
OPTISCALER=0

GAME_CMD=()
GAME_ENV=(
    "PROTON_PRIORITY_HIGH=1"
    "PROTON_LOCAL_SHADER_CACHE=1"
    "PROTON_DISCORD_BRIDGE=1"

    "PROTON_DXVK_LOWLATENCY=1"
    "PROTON_VKD3D_LOWLATENCY=1"
    "LOW_LATENCY_LAYER=1"
    "LOW_LATENCY_LAYER_REFLEX=1"
)

while [[ $# -gt 0 ]]; do
    case "$1" in 
        --optiscaler) OPTISCALER=1; shift ;;

        --mangohud) MANGOHUD_TYPE=1; shift ;;
        --mangoapp) MANGOHUD_TYPE=2; shift ;;

        --nvapi) NVAPI_STATUS=1; shift ;;
        --no-nvapi) NVAPI_STATUS=2; shift ;;

        --gamescope) GAMESCOPE=1; shift ;;
        --xwayland) WAYLAND=0; shift;;

        --) shift; GAME_CMD+=("$@"); break ;;
        -*) GAME_CMD+=("$@"); break ;;
        *) GAME_CMD+=("$@"); break ;;
    esac
done

if [[ ${#GAME_CMD[@]} -eq 0 ]]; then
    echo "Error: No game executable provided."
    exit 1
fi

if [[ $NVAPI_STATUS -eq 1 ]]; then
    GAME_ENV+=("PROTON_ENABLE_NVAPI=1")
elif [[ $NVAPI_STATUS -eq 2 ]]; then
    GAME_ENV+=("PROTON_DISABLE_NVAPI=1")
fi

if [[ $OPTISCALER -eq 1 ]]; then
    OPTI_CONFIG_ARRAY=(
        "Upscalers.Dx11Upscaler=fsr31_12"
        "Upscalers.Dx12Upscaler=fsr31"
        "Upscalers.VulkanUpscaler=fsr31_12"
        "FrameGen.Enabled=true"
        "FrameGen.FGInput=DLSSG"
        "FrameGen.FGOutput=XeFG"
        "FSR.Fsr4Update=auto"
        "FSR.Fsr4ForceEnableInt8=true"
        "Menu.ShortcutKey=0x24"
        "Menu.FpsShortcutKey=0x2d"
    )

    printf -v OPTI_CONFIG_STRING "%s;" "${OPTI_CONFIG_ARRAY[@]}"
    OPTI_CONFIG_STRING="${OPTI_CONFIG_STRING%;}"

    GAME_ENV+=(
        "PROTON_USE_OPTISCALER=1"
        "PROTON_OPTISCALER_CONFIG=${OPTI_CONFIG_STRING}"
        "WINEDLLOVERRIDES=dxgi=n,b"
    )
fi

if [[ "$SESSION_TYPE" == "steamos" ]]; then
    WAYLAND=0
    GAMESCOPE=0
    MANGOHUD_TYPE=0

    LAUNCH_CMD=()

    sudo systemctl stop ananicy-cpp
    sudo scxctl switch --sched cake
else
    LAUNCH_CMD=(app2unit --)
fi

if [[ $WAYLAND -eq 1 ]]; then
    GAME_ENV+=("PROTON_ENABLE_WAYLAND=1")
fi

WRAPPER=(gamemoderun "${GAME_CMD[@]}")
if [[ $MANGOHUD_TYPE -eq 1 ]]; then
    WRAPPER=(gamemoderun mangohud "${GAME_CMD[@]}")
fi

if [[ $GAMESCOPE -eq 1 ]]; then
    CURRENT_HZ=$(hyprctl monitors -j 2>/dev/null | jq '.[] | select(.focused) | .refreshRate | round' 2>/dev/null)
    if [[ -z "$CURRENT_HZ" ]]; then
        CURRENT_HZ="60"
    fi
    
    GAMESCOPE_ARGS=(
        -W 1920 -H 1080 -f -r "$CURRENT_HZ" --force-grab-cursor
    )

    if [[ $CURRENT_HZ -eq 165 ]]; then
        GAMESCOPE_ARGS+=("--adaptive-sync")
    fi

    if [[ $MANGOHUD_TYPE -eq 2 ]]; then
        GAMESCOPE_ARGS+=("--mangoapp")
    fi

    LAUNCH_CMD+=(gamescope "${GAMESCOPE_ARGS[@]}" --)
fi

LAUNCH_CMD+=(env "${GAME_ENV[@]}" "${WRAPPER[@]}")

exec booster "${LAUNCH_CMD[@]}"
