# --- Core components ---

[[components]]
name = "hypr"
default = true
packages = [
    "hyprland",
    "xdg-desktop-portal-hyprland",
    "xdg-desktop-portal-gtk",
    "ttf-jetbrains-mono-nerd",
]
post_install = [
    "hyprctl reload >/dev/null",
    "hyprpm update",
    "hyprpm reload"
]
post_update = [
    "hyprctl reload >/dev/null",
    "hyprpm update",
    "hyprpm reload"
]
[[components.entries]]
src = "hypr"
dest = "$XDG_CONFIG_HOME/hypr"
[[components.entries]]
src = "xdg-desktop-portal"
dest = "$XDG_CONFIG_HOME/xdg-desktop-portal"

[[components]]
name = "caelestia"
default=true
packages = ["local:shell"]
post_install = [
    "test -f ${XDG_STATE_HOME:-$HOME/.local/state}/caelestia/scheme.json || caelestia scheme set -n caelestia",
    "caelestia shell -k >/dev/null; sleep 1; caelestia shell -d >/dev/null",
]
[[components.entries]]
src = "caelestia"
dest = "$XDG_CONFIG_HOME/caelestia"

[[components]]
name = "fish"
default = true
packages = ["fish", "eza", "zoxide", "direnv"]
[[components.entries]]
src = "fish"
dest = "$XDG_CONFIG_HOME/fish"

[[components]]
name = "foot"
default = true
packages = ["foot", "fish", "ttf-jetbrains-mono-nerd"]
[[components.entries]]
src = "foot"
dest = "$XDG_CONFIG_HOME/foot"

[[components]]
name = "fastfetch"
default = true
packages = ["fastfetch"]
[[components.entries]]
src = "fastfetch"
dest = "$XDG_CONFIG_HOME/fastfetch"

[[components]]
name = "yazi"
default = true
packages = ["yazi", "7zip", "ffmpeg"]
[[components.entries]]
src = "yazi"
dest = "$XDG_CONFIG_HOME/yazi"

[[components]]
name = "pacseek"
default = true
packages = ["pacseek"]
[[components.entries]]
src = "pacseek"
dest = "$XDG_CONFIG_HOME/pacseek"

[[components]]
name = "system"
default = true
packages = ["btop", "nvtop", "ncdu"]
post_install = ["killall -USR2 btop 2>/dev/null || true"]
post_update = ["killall -USR2 btop 2>/dev/null || true"]
[[components.entries]]
src = "btop"
dest = "$XDG_CONFIG_HOME/btop"

[[components]]
name = "micro"
default = true
packages = ["micro"]
[[components.entries]]
src = "micro"
dest = "$XDG_CONFIG_HOME/micro"

[[components]]
name = "thunar"
default = true
packages = ["thunar", "thunar-archive-plugin", "sshfs"]
[[components.entries]]
src = "thunar"
dest = "$XDG_CONFIG_HOME/Thunar"
[[components.entries]]
src = "mimeapps.list"
dest = "$XDG_CONFIG_HOME/mimeapps.list"
[[components.entries]]
src = "xfce4"
dest = "$XDG_CONFIG_HOME/xfce4"

[[components]]
name = "starship"
default = true
packages = ["starship"]
[[components.entries]]
src = "starship.toml"
dest = "$XDG_CONFIG_HOME/starship.toml"

[[components]]
name = "udiskie"
default = true
packages = ["udiskie"]
[[components.entries]]
src = "udiskie"
dest = "$XDG_CONFIG_HOME/udiskie"

[[components]]
name = "gtk"
default = true
packages = ["adw-gtk-theme", "papirus-icon-theme", "papirus-folders"]

[[components]]
name = "qt"
default = true
packages = [
    "qtengine-git",
    "frameworkintegration",
    "darkly-bin",
    "papirus-icon-theme",
    "papirus-folders",
]

[[components]]
name = "auth"
default = true
packages = ["gnome-keyring"]

[[components]]
name = "network"
default = true
packages = ["networkmanager"]

[[components]]
name = "bluetooth"
default = true
packages = ["bluez", "bluez-utils"]

[[components]]
name = "pipewire"
default = true
packages = [
    "pipewire",
    "pipewire-pulse",
    "pipewire-audio",
    "pipewire-alsa",
    "pipewire-jack",
    "wireplumber",
    "pavucontrol",
    "playerctl"
]
[[components.entries]]
src = "wireplumber"
dest = "$XDG_CONFIG_HOME/wireplumber"

[[components]]
name = "clipboard"
default = true
packages = ["wl-clipboard", "cliphist", "wtype"]

[[components]]
name = "fonts"
default = true
packages = ["noto-fonts", "noto-fonts-cjk", "noto-fonts-emoji"]

[[components]]
name = "gaming"
default = true
packages = ["cachyos-gaming-applications", "gamemode", "hyprland-focused-booster"]
post_install = [
    "systemctl --user enable --now hyprland-focused-booster.service"
]
[[components.entries]]
src = "gaming/gamerun"
dest = "$XDG_BIN_HOME/gamerun"
[[components.entries]]
src = "mangohud"
dest = "$XDG_CONFIG_HOME/MangoHud"
[[components.entries]]
src = "gaming/gamemode.ini"
dest = "/usr/share/gamemode/gamemode.ini"
sudo=true
[[components.entries]]
src = "gaming/scx_loader.toml"
dest = "/etc/scx_loader/config.toml"
sudo=true
[[components.entries]]
src = "gaming/gaming"
dest = "/etc/sudoers.d/gaming"
sudo=true

[[components]]
name = "systemd"
default = true
packages = ["uwsm", "app2unit"]
[[components.entries]]
src = "uwsm"
dest = "$XDG_CONFIG_HOME/uwsm"
[[components.entries]]
src = "environment.d"
dest = "$XDG_CONFIG_HOME/environment.d"

[[components]]
name = "tools"
default = true
packages = [
    "git",
    "curl",
    "trash-cli",
    "jq",
    "lazygit",
    "bat",
    "ripgrep",
    "ydotool",
    "hyprpicker",
    "hyprsunset",
    "xdg-user-dirs",
]
post_install = [
    "systemctl --user enable --now hyprsunset", 
    "xdg-user-dirs-update", 
    'git clone https://github.com/GwynnN7/Wallpaper "$HOME/Pictures/Wallpaper" 2>/dev/null || git -C "$HOME/Pictures/Wallpaper" pull'
    ]

# --- Optional components ---

[[components]]
name = "software"
packages = ["tidal-hifi-bin", "zen-browser-bin", "telegram-desktop", "equibop"]

[[components]]
name = "development"
packages = ["visual-studio-code-bin", "git", "github-cli", "android-tools", "rocm-smi-lib"]
post_install = [
    "code --install-extension $CAELESTIA_DOTS/vscode/caelestia-vscode-integration/caelestia-vscode-integration-*.vsix",
]
[[components.entries]]
src = "vscode/settings.json"
dest = "$XDG_CONFIG_HOME/Code/User/settings.json"
[[components.entries]]
src = "vscode/keybindings.json"
dest = "$XDG_CONFIG_HOME/Code/User/keybindings.json"
[[components.entries]]
src = "vscode/flags.conf"
dest = "$XDG_CONFIG_HOME/code-flags.conf"

[[components]]
name = "applications"
packages = ["gimp", "vlc", "celluloid", "loupe", "evince", "file-roller", "gparted", "xorg-xhost"]

[[components]]
name = "sddm"
packages = [
    "sddm",
    "caelestia-sddm-minimalistv2-git",
    "layer-shell-qt"
]
post_install = [
    "sudo systemctl daemon-reload",
    "sudo systemctl enable --now sddm.service",
    "sudo /usr/share/sddm/themes/caelestia/scripts/sync.sh >/dev/null"
]
post_update = [
    "sudo /usr/share/sddm/themes/caelestia/scripts/sync.sh >/dev/null"
]
[[components.entries]]
src = "sddm/caelestia.conf"
dest = "/etc/sddm.conf.d/caelestia.conf"
sudo = true
[[components.entries]]
src = "sddm/sddm.lua"
dest = "/opt/hypr/sddm.lua"
sudo = true
[[components.entries]]
src = "sddm/caelestia-sddm"
dest = "/etc/sudoers.d/caelestia-sddm"
sudo = true

[[components]]
name = "openrgb"
packages = [
    "openrgb-git",
    "caelestia-rgb-sync"
]
post_install = [
    "caelestia-rgb-sync init",
    "caelestia-rgb-sync calibrate device",
    "caelestia-rgb-sync calibrate global",
    "caelestia-rgb-sync enable"
]
post_update = [
    "caelestia-rgb-sync apply"
]

[[components]]
name = "kdeconnect"
packages = ["kdeconnect", "local:kdeconnect"]
post_install = [
    "systemctl --user stop hypr-kdeconnect-portal.service",
    "systemctl --user daemon-reload",
    "systemctl --user restart xdg-desktop-portal"
]

[[components]]
name = "hyprpm"
packages = []
post_install = [
    "hyprpm purge-cache",
    "hyprpm update",
    "hyprpm add https://github.com/zjeffer/split-monitor-workspaces || true",
    "hyprpm add https://github.com/yayuuu/hyprland-scroll-overview || true",
    "hyprpm add https://github.com/gfhdhytghd/hymission || true",
    "hyprpm enable split-monitor-workspaces || true",
    "hyprpm enable scrolloverview || true",
    "hyprpm enable hymission || true",
    "hyprpm reload"
]

[[components]]
name = "cortana"
packages = ["dotnet-sdk"]
post_install = [
    'git clone https://github.com/GwynnN7/Cortana "$HOME/Projects/Cortana" 2>/dev/null || git -C "$HOME/Projects/Cortana" pull',
    'mkdir -p "$HOME/Projects/Cortana/CortanaDesktop/out"',
    "systemctl --user daemon-reload",
    "systemctl --user enable cortana-desktop.service"
]
[[components.entries]]
src = "cortana/Settings.json"
dest = "$XDG_CONFIG_HOME/cortana/Settings.json"
[[components.entries]]
src = "cortana/cortana"
dest = "$XDG_BIN_HOME/cortana"
[[components.entries]]
src = "cortana/cortana-desktop.service"
dest = "$XDG_CONFIG_SERVICE/cortana-desktop.service"
[[components.entries]]
src = "cortana/efibootmgr"
dest = "/etc/sudoers.d/efibootmgr"
sudo = true

[[components]]
name = "retrodeck"
packages = ["flatpak"]
post_install = [
    "flatpak install net.retrodeck.retrodeck",
    "flatpak override --user --talk-name=org.freedesktop.Flatpak net.retrodeck.retrodeck",
    "mkdir -p /home/gwynn7/Games/Retrodeck/Eden",
    "mkdir -p /home/gwynn7/Games/Retrodeck/retrodeck/apps",
]
[[components.entries]]
src = "retrodeck/es_systems.xml"
dest = "$HOME/.var/app/net.retrodeck.retrodeck/config/ES-DE/custom_systems/es_systems.xml"
[[components.entries]]
src = "retrodeck/Switch.sh"
dest = "/home/gwynn7/Games/Retrodeck/retrodeck/apps/Switch.sh"