bind = $kbScrollWin, right, layoutmsg, move +col
bind = $kbScrollWin, left, layoutmsg, move -col
bind = $kbScrollWin, D, layoutmsg, move +col
bind = $kbScrollWin, A, layoutmsg, move -col

bind = $kbMoveScrollWin, right, layoutmsg, swapcol r
bind = $kbMoveScrollWin, left, layoutmsg, swapcol l
bind = $kbMoveScrollWin, D, layoutmsg, swapcol r
bind = $kbMoveScrollWin, A, layoutmsg, swapcol l