# ## Shell keybinds
# Launcher
bindi = Super, Super_L, global, caelestia:launcher
bindin = Super, catchall, global, caelestia:launcherInterrupt
bindin = Super, mouse:272, global, caelestia:launcherInterrupt
bindin = Super, mouse:273, global, caelestia:launcherInterrupt
bindin = Super, mouse:274, global, caelestia:launcherInterrupt
bindin = Super, mouse:275, global, caelestia:launcherInterrupt
bindin = Super, mouse:276, global, caelestia:launcherInterrupt
bindin = Super, mouse:277, global, caelestia:launcherInterrupt
bindin = Super, mouse_up, global, caelestia:launcherInterrupt
bindin = Super, mouse_down, global, caelestia:launcherInterrupt

# Misc
bind = $kbSession, global, caelestia:session
bind = $kbShowSidebar, global, caelestia:sidebar
bindl = $kbClearNotifs, global, caelestia:clearNotifs
bind = $kbShowPanels, global, caelestia:showall
bind = $kbLock, global, caelestia:lock

# Restore lock
bindl = $kbRestoreLock, exec, caelestia shell -d
bindl = $kbRestoreLock, global, caelestia:lock
bindl = Super+Shift, L, exec, systemctl suspend-then-hibernate

# Brightness
bindl = , XF86MonBrightnessUp, global, caelestia:brightnessUp
bindl = , XF86MonBrightnessDown, global, caelestia:brightnessDown

# Kill/restart
bind = Ctrl+Alt, Delete, exec, qs -c caelestia kill
bind = Ctrl+Super, Delete, exec, qs -c caelestia kill; sleep .1; caelestia shell -d
