# Apps
bind = $kbTerminal, exec, app2unit -- $terminal
bind = $kbBrowser, exec, app2unit -- $browser
bind = $kbEditor, exec, app2unit -- $editor
bind = $kbFileExplorer, exec, app2unit -- $fileExplorer
bind = $kbYazi, exec, app2unit -- $terminal fish -i -c "yazi"

# Utilities
bindl = Super, Print, exec, caelestia screenshot  # Full screen capture > clipboard
bindl = , Print, global, caelestia:screenshotFreeze  # Capture region (freeze)
bindl = Shift+Alt, S, global, caelestia:screenshotFreeze  # Capture region (freeze)
bindl = Super+Alt+Shift, S, global, caelestia:screenshot  # Capture region
bind = Super+Alt, R, exec, caelestia record -s  # Record screen with sound
bind = Shift+Alt, R, exec, caelestia record  # Record screen
bind = Super+Shift+Alt, R, exec, caelestia record -r  # Record region
bind = Shift+Alt, C, exec, hyprpicker -a  # Color picker

# Clipboard and emoji picker
bind = Super, V, exec, caelestia shell clipboard toggle

bind = Super+Alt, V, exec, pkill fuzzel || caelestia clipboard -d
bind = Super, Period, exec, pkill fuzzel || caelestia emoji -p
bindl = Ctrl+Shift+Alt, V, exec, sleep 0.5s && ydotool type -d 1 "$(cliphist list | head -1 | cliphist decode)"  # Alternate paste
