# Window actions

bind = $kbFocusWin, left, movefocus, l
bind = $kbFocusWin, right, movefocus, r
bind = $kbFocusWin, up, movefocus, u
bind = $kbFocusWin, down, movefocus, d
bind = $kbMoveWin, left, movewindow, l
bind = $kbMoveWin, right, movewindow, r
bind = $kbMoveWin, up, movewindow, u
bind = $kbMoveWin, down, movewindow, d

binde = Super, Minus, layoutmsg, colresize -0.15
binde = Super, Equal, layoutmsg, colresize +0.15
binde = Super+Shift, Minus, layoutmsg, colresize -conf
binde = Super+Shift, Equal, layoutmsg, colresize +conf
binde = Super+Shift, Minus, resizeactive, 0 -10%
binde = Super+Shift, Equal, resizeactive, 0 10% 
binde = Super+Alt, left, layoutmsg, colresize -0.15
binde = Super+Alt, right, layoutmsg, colresize +0.15
binde = Super+Alt, A, layoutmsg, colresize -0.15
binde = Super+Alt, D, layoutmsg, colresize +0.15
binde = Super+Alt, up, resizeactive, 0 -10%
binde = Super+Alt, down, resizeactive, 0 10%
bindm = Super, mouse:272, movewindow
bindm = Super, mouse:273, resizewindow
bind = $kbWindowPip, exec, caelestia resizer pip  # Move window to picture-in-picture mode
bind = $kbPinWindow, pin
bind = $kbWindowFullscreen, fullscreen, 0
bind = $kbWindowBorderedFullscreen, fullscreen, 1  # Fullscreen with borders
bind = $kbToggleWindowFloating, togglefloating,
bind = $kbCloseWindow, killactive,

# Window groups
binde = $kbWindowGroupCycleNext, cyclenext
binde = $kbWindowGroupCyclePrev, cyclenext, prev
binde = Ctrl+Alt, Tab, changegroupactive, f
binde = Ctrl+Shift+Alt, Tab, changegroupactive, b
bind = $kbToggleGroup, togglegroup
bind = $kbUngroup, moveoutofgroup