[mgr]
ratio          = [ 1, 2, 5 ]

[preview]
wrap            = "yes"
tab_size        = 2
max_width       = 600
max_height      = 900
image_delay     = 50
image_quality   = 90

[input]
cursor_blink = true

[opener]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = '"$EDITOR" "$@"', block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]

[open]
prepend_rules = [
	{ url = "*.json", use = "edit" },
	{ url = "*.sh", use = "edit" },
	{ url = "*.toml", use = "edit" },
	{ url = "*.y*ml", use = "edit" },
	{ url = "*config", use = "edit" },
	{ url = "*.cfg", use = "edit" },
	{ url = "*env", use = "edit" },
	{ url = "*.d", use = "edit" },
	{ url = "*.md", use = "edit" },
	{ url = "*.txt", use = "edit" },
	{ url = ".zsh*", use = "edit" },
	{ url = "*.ini", use = "edit" },
	{ url = "*.lua", use = "edit" },
	{ url = "*.xml", use = "edit" },
	{ url = "*.log", use = "edit" },
	{ url = "*.ods", use = "open" },
	{ url = "*.pdf", use = "open" },
	{ url = "*.mp3", use = "play" },
]

append_rules = [
	{ url = "*", use = "edit" },
	{ url = "*/", use = "open" },
]