general {
    layout = scrolling

    allow_tearing = 0

    gaps_workspaces = $workspaceGaps
    gaps_in = $windowGapsIn
    gaps_out = $windowGapsOut
    border_size = $windowBorderSize

    col.active_border = $activeWindowBorderColour
    col.inactive_border = $inactiveWindowBorderColour

    monitor=eDP-1, preferred, auto, 1
    #monitor=HDMI-A-1, preferred, auto, 1, mirror, eDP-1
}

dwindle {
	preserve_split = true
	smart_split = false
	smart_resizing = true
}
