general {
    layout = scrolling

    allow_tearing = true  # Allows `immediate` window rule to work

    gaps_workspaces = $workspaceGaps
    gaps_in = $windowGapsIn
    gaps_out = $windowGapsOut
    border_size = $windowBorderSize

    col.active_border = $activeWindowBorderColour
    col.inactive_border = $inactiveWindowBorderColour

    monitor=DP-1, 1920x1080@165.00Hz, 0x0, 1
	monitor=HDMI-A-1, 1920x1080@60.00Hz, 1920x0, 1
}

dwindle {
	preserve_split = true
	smart_split = false
	smart_resizing = true
}
