plugin {
    split-monitor-workspaces {
        count = 8
        keep_focused = 0
        enable_wrapping = 0
        enable_notifications = 0
        enable_persistent_workspaces = 0
    }

    scrolloverview {
        gesture_distance = 300
        scale = 0.5
        workspace_gap = 100
        wallpaper = 0
        blur = false

        shadow {
            enabled = false
        }
    }

    hymission {
            outer_padding_top = 24
            outer_padding_right = 32
            outer_padding_bottom = 32
            outer_padding_left = 24
            row_spacing = 28
            column_spacing = 28
            layout_engine = grid
    
            expand_selected_window = 1
            overview_focus_follows_mouse = 1
            multi_workspace_sort_recent_first = 0
            toggle_switch_mode = 0
            one_workspace_per_row = 1
            only_active_workspace = 1
    
            workspace_strip_anchor = top
            workspace_strip_thickness = 140
            workspace_strip_gap = 0
        }
 }
