plugin {
    split-monitor-workspaces {
        count = 4
        keep_focused = 0
        enable_wrapping = 0
        enable_notifications = 0
        enable_persistent_workspaces = 0
    }

    scrolloverview {
        gesture_distance = 300
        scale = 0.5
        workspace_gap = 100
        wallpaper = 0
        blur = false

        shadow {
            enabled = false
        }
    }
 }
