plugin {
    split-monitor-workspaces {
        count = 4
        keep_focused = 0
        enable_wrapping = 0
        enable_notifications = 0
        enable_persistent_workspaces = 1
        link_monitors = 0
        monitor_priority = DP-1, HDMI-A-1
    }

    scrolloverview {
        gesture_distance = 300
        scale = 0.5
        workspace_gap = 100
        wallpaper = 2
        blur = true

        shadow {
            enabled = true
            range = 50
            render_power = 3
            color = rgba(1a1a1aee)
        }
    }
 }
