#!/bin/bash

sudo mkdir -p /run/greetd

SESSION_NAME=$(cat /run/greetd/next-session 2>/dev/null || echo "hyprland-uwsm.desktop")
SESSION_PATH="/usr/share/wayland-sessions/$SESSION_NAME"

EXEC_CMD=$(grep -m 1 '^Exec=' "$SESSION_PATH" | cut -d '=' -f 2-)
exec $EXEC_CMD
