$hypr = ~/.config/hypr
$hl = $hypr/hyprland

# Variables (colours + other vars)
exec = cp -L --no-preserve=mode --update=none $hypr/scheme/default.conf $hypr/scheme/current.conf
source = $hypr/scheme/current.conf
source = $hypr/variables.conf

# Configs
source = $hl/env.conf
source = $hl/general.conf
source = $hl/input.conf
source = $hl/misc.conf
source = $hl/animations.conf
source = $hl/decoration.conf
source = $hl/group.conf
source = $hl/execs.conf
source = $hl/rules.conf
source = $hl/gestures.conf
source = $hl/scrolling.conf
source = $hl/plugins.conf

source = $hl/keybinds/keybinds.conf
source = $hl/keybinds/shell.conf
source = $hl/keybinds/scrolling.conf
source = $hl/keybinds/workspaces.conf
source = $hl/keybinds/window.conf
source = $hl/keybinds/plugins.conf
source = $hl/keybinds/media.conf
source = $hl/keybinds/utility.conf