general {
    lock_cmd = qs -c caelestia ipc call lock lock
    before_sleep_cmd = qs -c caelestia ipc call lock lock
}

listener {
    timeout = 300
    on-timeout = cortana idle on
    on-resume = cortana idle off
}

listener {
    timeout = 900
    on-timeout = qs -c caelestia ipc call lock lock
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
