[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

[Wayland]
CompositorCommand=start-hyprland -- -c /opt/hypr/sddm.lua

[Theme]
Current=caelestia

[Autologin]
User=gwynn7
Session=hyprland-uwsm