[devices]
hiddenDevices=/dev/nvme0n1p2, /dev/sdb1, /dev/sdb4, /dev/nvme0n1p1

[places]
hiddenPlaces=/home/gwynn7/Games, /home/gwynn7/Storage, /home/gwynn7/Music, /home/gwynn7/Videos

[preferences]
expandableFolders=false
placesIconSize=20
showNetworkSection=false

[session]
currentTab=0
iconZoomLevel=80
showHidden=false
tabPaths=/home/gwynn7
viewMode=0