#!/usr/bin/env bash

USE_FG=0
CLEAN_ARGS=()

for arg in "$@"; do
    if [[ "$arg" == "--fg" ]]; then
        USE_FG=1
    else
        CLEAN_ARGS+=("$arg")
    fi
done

if ! command -v powerprofilesctl &>/dev/null; then 
    echo "Error: powerprofilesctl not found" >&2
    exit 1 
fi


GS_ARGS=(gamescope -W 1920 -H 1080 -f --adaptive-sync --mangoapp -r 165 --)

ENV_VARS=(
    env PROTON_ENABLE_WAYLAND=1
    PROTON_PRIORITY_HIGH=1 
    ENABLE_LAYER_MESA_ANTI_LAG=1
    
    DXVK_FRAME_RATE=162
    DXVK_FRAME_PACE=low-latency-vrr-165
    
    VKD3D_FRAME_RATE=162
)

if [ "$USE_FG" = "1" ]; then
    ENV_VARS+=(PROTON_ENABLE_NVAPI=1)
    WRAPPER=(/home/gwynn7/.local/share/goverlay/fgmod/fgmod -- env gamemoderun)
else
    ENV_VARS+=(PROTON_DISABLE_NVAPI=1)
    WRAPPER=(gamemoderun)
fi

LAUNCH_CMD=("${GS_ARGS[@]}" "${ENV_VARS[@]}" "${WRAPPER[@]}" "${CLEAN_ARGS[@]}")

if ! powerprofilesctl list | grep -q 'performance:'; then 
    exec "${LAUNCH_CMD[@]}"
else 
    if [ -n "$GAME_PERFORMANCE_SCREENSAVER_ON" ]; then 
        exec powerprofilesctl launch -p performance -r "CachyOS wrapper" -- "${LAUNCH_CMD[@]}"
    else 
        exec systemd-inhibit --why "Gaming" powerprofilesctl launch -p performance -r "CachyOS wrapper" -- "${LAUNCH_CMD[@]}"
    fi
fi
