#!/bin/bash

DIRECTION=$1

PREFERRED_PLAYERS=("tidal-hifi" "spotify" "celluloid" "mpv" "vlc")
TARGET_PLAYER=""

RUNNING_PLAYERS=$(playerctl -l 2>/dev/null)

for p in "${PREFERRED_PLAYERS[@]}"; do
    if echo "$RUNNING_PLAYERS" | grep -iq "^$p"; then
        TARGET_PLAYER="$p"
        break
    fi
done

pw-play /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga &

if [ -n "$TARGET_PLAYER" ]; then
    CURRENT_VOL=$(playerctl -p "$TARGET_PLAYER" volume 2>/dev/null || echo "0.5")
    
    NEW_VOL=$(awk -v cv="$CURRENT_VOL" -v dir="$DIRECTION" 'BEGIN {
        nv = (dir == "+") ? cv + 0.05 : cv - 0.05;
        if (nv > 1.0) nv = 1.0;
        if (nv < 0.0) nv = 0.0;
        printf "%.2f\n", nv
    }')
    
    playerctl -p "$TARGET_PLAYER" volume "$NEW_VOL"
    
    VOL=$(awk -v nv="$NEW_VOL" 'BEGIN { printf "%.0f\n", nv * 100 }')
    
    PLAYER_NAME=$(playerctl -p "$TARGET_PLAYER" metadata --format "{{playerName}}" 2>/dev/null | awk '{print toupper(substr($0,1,1)) substr($0,2)}')
    if [ -z "$PLAYER_NAME" ]; then
        PLAYER_NAME="Media"
    fi

    caelestia shell toaster info "Media Player" "$PLAYER_NAME Volume $VOL%" music_note
    
else
	if [ "$DIRECTION" = "+" ]; then
    	 wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
    else
    	wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
    fi
fi
