bindl = Super, F1, exec, cortana api -act on devices/lamp | cortana notify
bindl = Super, F2, exec, cortana api -act off devices/lamp | cortana notify
bindl = Super, F5, exec, cortana api -val 0 settings/automaticmode | cortana notify
bindl = Super, F6, exec, cortana api -val 1 settings/automaticmode | cortana notify