exec = hyprctl dispatch submap global
submap = global

source = $hl/keybinds/shell.conf
source = $hl/keybinds/scrolling.conf
source = $hl/keybinds/workspaces.conf
source = $hl/keybinds/window.conf
source = $hl/keybinds/plugins.conf
source = $hl/keybinds/media.conf
source = $hl/keybinds/utility.conf

# Testing
bindl = Super+Alt, Return, exec, notify-send -u low -i dialog-information-symbolic 'Test notification' "Here's a really long message to test truncation and wrapping\nYou can middle click or flick this notification to dismiss it!" -a 'Shell' -A "Test1=I got it!" -A "Test2=Another action"
