source = $hl/keybinds/shell.conf
source = $hl/keybinds/scrolling.conf
source = $hl/keybinds/workspaces.conf
source = $hl/keybinds/window.conf
source = $hl/keybinds/plugins.conf
source = $hl/keybinds/media.conf
source = $hl/keybinds/utility.conf
source = $hl/keybinds/cortana.conf

bind = Super, Home, submap, passthru
submap = passthru
bind = Super, Home, submap, reset 
submap = reset
