bind = $kbFocus, right, layoutmsg, focus r
bind = $kbFocus, left, layoutmsg, focus l
bind = $kbFocus, D, layoutmsg, focus r
bind = $kbFocus, A, layoutmsg, focus l

bind = $kbMove, right, layoutmsg, swapcol r
bind = $kbMove, left, layoutmsg, swapcol l
bind = $kbMove, D, layoutmsg, swapcol r
bind = $kbMove, A, layoutmsg, swapcol l

bind = $kbMoveWin, left, layoutmsg, consume_or_expel prev
bind = $kbMoveWin, right, layoutmsg, consume_or_expel next
bind = $kbMoveWin, A, layoutmsg, consume_or_expel prev
bind = $kbMoveWin, D, layoutmsg, consume_or_expel next

bind = Super, Z, layoutmsg, fit visible
bind = Super+Alt, Z, exec, hyprctl getoption scrolling:focus_fit_method | grep -q 'int: 1' && hyprctl keyword scrolling:focus_fit_method 0 || hyprctl keyword scrolling:focus_fit_method 1
