bind = $kbScrollWin, right, layoutmsg, focus r
bind = $kbScrollWin, left, layoutmsg, focus l
bind = $kbScrollWin, D, layoutmsg, focus r
bind = $kbScrollWin, A, layoutmsg, focus l

bind = $kbMoveScrollWin, right, layoutmsg, swapcol r
bind = $kbMoveScrollWin, left, layoutmsg, swapcol l
bind = $kbMoveScrollWin, D, layoutmsg, swapcol r
bind = $kbMoveScrollWin, A, layoutmsg, swapcol l

bind = Super+Shift+Alt, left, layoutmsg, consume_or_expel prev
bind = Super+Shift+Alt, A, layoutmsg, consume_or_expel prev
bind = Super+Shift+Alt, right, layoutmsg, consume_or_expel next
bind = Super+Shift+Alt, D, layoutmsg, consume_or_expel next
bind = Super+Shift+Alt, up, movewindow, u
bind = Super+Shift+Alt, down, movewindow, d

bind = Super, X, layoutmsg, fit visible
bind = Super, C, exec, hyprctl getoption scrolling:focus_fit_method | grep -q 'int: 1' && hyprctl keyword scrolling:focus_fit_method 0 || hyprctl keyword scrolling:focus_fit_method 1
