# ## Shell keybinds
# Launcher
bindir = Super, Super_L, exec, caelestia shell drawers toggle launcher

# Misc
bind = $kbSession, global, caelestia:session
bind = Super, F3, global, caelestia:session
bind = $kbShowSidebar, global, caelestia:sidebar
bind = $kbShowPanels, global, caelestia:showall
bind = $kbLock, global, caelestia:lock

# Restore lock
bindl = $kbRestoreLock, exec, caelestia shell -d
bindl = $kbRestoreLock, global, caelestia:lock
bindl = Super+Shift, L, exec, systemctl suspend

# Brightness
bindl = , XF86MonBrightnessUp, global, caelestia:brightnessUp
bindl = , XF86MonBrightnessDown, global, caelestia:brightnessDown

# Kill/restart
bind = Ctrl+Alt, Delete, exec, caelestia shell -k
bind = Ctrl+Super, Delete, exec, caelestia shell -k; sleep 1; caelestia shell -d
