# Apps
bind = $kbTerminal, exec, app2unit -- $terminal
bind = $kbBrowser, exec, app2unit -- $browser
bind = $kbFileExplorer, exec, app2unit -- $fileExplorer
bind = $kbYazi, exec, app2unit -- $terminal fish -C "y"

# Utilities
bindl = , Print, exec, caelestia screenshot  # Full screen capture > clipboard
bindl = Super, Print, global, caelestia:screenshotFreeze  # Capture region (freeze)
bindl = Shift+Alt, S, global, caelestia:screenshotFreeze  # Capture region (freeze)
bindl = Super+Alt+Shift, S, global, caelestia:screenshot  # Capture region
bind = Super+Alt, R, exec, caelestia record -s  # Record screen with sound
bind = Shift+Alt, R, exec, caelestia record  # Record screen
bind = Super+Shift+Alt, R, exec, caelestia record -r  # Record region
bind = Shift+Alt, C, exec, hyprpicker -a  # Color picker

# Clipboard and emoji picker
bind = Super, V, global, caelestia:clipboard
bind = Super, Period, global, caelestia:emoji
bind = Super, K, global, caelestia:keybinds
bind = Super+Alt, V, exec, pkill fuzzel || caelestia clipboard -d
bind = Super+Alt, Period, exec, pkill fuzzel || caelestia emoji -p
