# Window actions

bind = $kbFocus, X, focusmonitor, +1
bind = $kbMove, X, split-changemonitor, next

bind = $kbFocusWin, up, movefocus, u
bind = $kbFocusWin, down, movefocus, d
bind = $kbFocusWin, left, movefocus, l
bind = $kbFocusWin, right, movefocus, r
bind = $kbFocusWin, W, movefocus, u
bind = $kbFocusWin, S, movefocus, d
bind = $kbFocusWin, A, movefocus, l
bind = $kbFocusWin, D, movefocus, r

bind = $kbMoveWin, up, movewindow, u
bind = $kbMoveWin, down, movewindow, d
bind = $kbMoveWin, W, movewindow, u
bind = $kbMoveWin, S, movewindow, d

binde = Super, Minus, layoutmsg, colresize -0.15
binde = Super, Equal, layoutmsg, colresize +0.15
binde = Super+Shift, Minus, layoutmsg, colresize -conf
binde = Super+Shift, Equal, layoutmsg, colresize +conf
binde = Super+Alt, Minus, resizeactive, 0 -10%
binde = Super+Alt, Equal, resizeactive, 0 10% 

binde = Super+Alt, left, layoutmsg, colresize -0.15
binde = Super+Alt, right, layoutmsg, colresize +0.15
binde = Super+Alt, A, layoutmsg, colresize -0.15
binde = Super+Alt, D, layoutmsg, colresize +0.15
binde = Super+Alt, up, resizeactive, 0 -10%
binde = Super+Alt, down, resizeactive, 0 10%

bindm = Super, mouse:272, movewindow
bindm = Super, mouse:273, resizewindow

bind = $kbPinWindow, pin
bind = $kbWindowFullscreen, fullscreen, 0
bind = $kbWindowBorderedFullscreen, exec, ~/.config/hypr/scripts/maximize-toggle.fish

bind = $kbToggleWindowFloating, togglefloating,
bindo = $kbToggleWindowFloating, exec, caelestia resizer pip

bind = $kbCloseWindow, killactive,
bindo = $kbCloseWindow, exec, hyprctl kill

# Window groups
binde = $kbWindowGroupCycleNext, cyclenext
binde = $kbWindowGroupCyclePrev, cyclenext, prev
binde = Ctrl+Alt, Tab, changegroupactive, f
binde = Ctrl+Shift+Alt, Tab, changegroupactive, b
bind = $kbToggleGroup, togglegroup
bind = $kbUngroup, moveoutofgroup
