# Go to workspace #
bind = $kbFocus, 1, split-workspace, 1
bind = $kbFocus, 2, split-workspace, 2
bind = $kbFocus, 3, split-workspace, 3
bind = $kbFocus, 4, split-workspace, 4

# Go to workspace -1/+1
bind = $kbFocus, mouse_down, exec, ~/.config/hypr/scripts/focus-workspace.fish up
bind = $kbFocus, mouse_up, exec, ~/.config/hypr/scripts/focus-workspace.fish down
bind = $kbFocus, up, exec, ~/.config/hypr/scripts/focus-workspace.fish up
bind = $kbFocus, down, exec, ~/.config/hypr/scripts/focus-workspace.fish down
bind = $kbFocus, W, exec, ~/.config/hypr/scripts/focus-workspace.fish up
bind = $kbFocus, S, exec, ~/.config/hypr/scripts/focus-workspace.fish down

# Move window to workspace #
bind = $kbMove, 1, split-movetoworkspace, 1
bind = $kbMove, 2, split-movetoworkspace, 2
bind = $kbMove, 3, split-movetoworkspace, 3
bind = $kbMove, 4, split-movetoworkspace, 4

# Move window to workspace -1/+1
bind = $kbMove, mouse_down, exec, ~/.config/hypr/scripts/move-workspace.fish down
bind = $kbMove, mouse_up, exec, ~/.config/hypr/scripts/move-workspace.fish up
bind = $kbMove, up, exec, ~/.config/hypr/scripts/move-workspace.fish up
bind = $kbMove, down, exec, ~/.config/hypr/scripts/move-workspace.fish down
bind = $kbMove, W, exec, ~/.config/hypr/scripts/move-workspace.fish up
bind = $kbMove, S, exec, ~/.config/hypr/scripts/move-workspace.fish down

# Special workspaces
bind = Ctrl, Escape, exec, caelestia toggle sysmon
bind = Super, F4, exec, caelestia toggle sysmon

bind = $kbFocus, Comma, exec, caelestia toggle specialws
bind = $kbMove, Comma, split-movetoworkspace, special

bindo = $kbFocus, C, exec, ~/.config/hypr/scripts/toggle-special.fish music
bind = $kbFocus, C, exec, ~/.config/hypr/scripts/toggle-special.fish communication
bind = $kbMove, Q, split-movetoworkspace, e+0
