# Go to workspace #
bind = $kbGoToWs, 1, split-workspace, 1
bind = $kbGoToWs, 2, split-workspace, 2
bind = $kbGoToWs, 3, split-workspace, 3
bind = $kbGoToWs, 4, split-workspace, 4

# Go to workspace -1/+1
bind = $kbGoToWs, mouse_down, split-workspace, -1
bind = $kbGoToWs, mouse_up, split-workspace, +1
bind = $kbGoToWs, up, split-workspace, -1
bind = $kbGoToWs, W, split-workspace, -1
bind = $kbGoToWs, down, split-workspace, +1
bind = $kbGoToWs, S, split-workspace, +1

# Move window to workspace #
bind = $kbMoveWinToWs, 1, split-movetoworkspace, 1
bind = $kbMoveWinToWs, 2, split-movetoworkspace, 2
bind = $kbMoveWinToWs, 3, split-movetoworkspace, 3
bind = $kbMoveWinToWs, 4, split-movetoworkspace, 4

# Move window to workspace -1/+1
bind = $kbMoveWinToWs, mouse_down, split-movetoworkspace, -1
bind = $kbMoveWinToWs, mouse_up, split-movetoworkspace, +1
bind = $kbMoveWinToWs, up, split-movetoworkspace, -1
bind = $kbMoveWinToWs, W, split-movetoworkspace, -1
bind = $kbMoveWinToWs, down, split-movetoworkspace, +1
bind = $kbMoveWinToWs, S, split-movetoworkspace, +1

# Special workspaces
bind = Ctrl, Escape, exec, caelestia toggle sysmon
bind = Super, F4, exec, caelestia toggle sysmon
bind = $kbGoToWs+Ctrl, Z, exec, caelestia toggle specialws
bind = $kbGoToWs+Alt, Z, exec, caelestia toggle music
bind = $kbGoToWs, Z, exec, caelestia toggle communication
bind = $kbMoveWinToWs, Z, split-movetoworkspace, special
bind = $kbMoveWinToWs, X, split-movetoworkspace, special:music
bind = $kbMoveWinToWs, C, split-movetoworkspace, special:communication
bind = $kbMoveWinToWs, Q, split-movetoworkspace, e+0
