monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.pci-0000_2d_00.1.pro-output-3"
      }
    ]
    actions = {
      update-props = {
        node.description = "LG Seconday Monitor"
        node.nick = "Seconday Monitor"
      }
    }
  },
  {
    matches = [
      {
        node.name = "alsa_output.pci-0000_2d_00.1.pro-output-7"
      }
    ]
    actions = {
      update-props = {
        node.description = "BenQ Primary Monitor"
        node.nick = "Primary Monitor"
      }
    }
  },
  {
    matches = [
      {
        node.name = "alsa_output.pci-0000_2f_00.4.iec958-stereo"
      },
      {
        node.name = "alsa_input.pci-0000_2f_00.4.analog-stereo"
      }
    ]
    actions = {
      update-props = {
        node.description = "Stereo Audio Controller"
        node.nick = "Stereo Audio Controller"
      }
    }
  },
  {
    matches = [
      {
        node.name = "alsa_output.usb-Logitech_PRO_X_SE_Gaming_Headset_000000000000-00.analog-stereo"
      },
      {
              node.name = "alsa_input.usb-Logitech_PRO_X_SE_Gaming_Headset_000000000000-00.mono-fallback"
            }
    ]
    actions = {
      update-props = {
        node.description = "Logitech G PRO X"
        node.nick = "Logitech G PRO X"
      }
    }
  },
  {
    matches = [
      {
        node.name = "alsa_output.pci-0000_2d_00.1.pro-output-9"
      },
      {
        node.name = "alsa_output.pci-0000_2d_00.1.pro-output-8"
      },
     {
		  node.name = "alsa_output.pci-0000_2d_00.1.pro-output-10"
		}
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  }
]
