$background = 130d0e
$onBackground = f6e0e5
$surface = 130d0e
$surfaceDim = 130d0e
$surfaceBright = 35292d
$surfaceContainerLowest = 000000
$surfaceContainerLow = 191114
$surfaceContainer = 20171a
$surfaceContainerHigh = 271d20
$surfaceContainerHighest = 2f2226
$onSurface = f6e0e5
$surfaceVariant = 2f2226
$onSurfaceVariant = b9a6ab
$outline = 827176
$outlineVariant = 534448
$inverseSurface = fff8f8
$inverseOnSurface = 5c5355
$shadow = 000000
$scrim = 000000
$surfaceTint = f2b6ca
$primary = f2b6ca
$primaryDim = e3a9bc
$onPrimary = 5d3343
$primaryContainer = 724555
$onPrimaryContainer = ffdae4
$inversePrimary = 805162
$primaryFixed = fec1d5
$primaryFixedDim = efb4c7
$onPrimaryFixed = 502837
$onPrimaryFixedVariant = 704354
$secondary = e2bdc8
$secondaryDim = d3afba
$onSecondary = 533942
$secondaryContainer = 4e343d
$onSecondaryContainer = dab6c1
$secondaryFixed = ffd9e4
$secondaryFixedDim = f0cbd6
$onSecondaryFixed = 523841
$onSecondaryFixedVariant = 70545d
$tertiary = ffe7fe
$tertiaryDim = fcd2fe
$onTertiary = 6d4d72
$tertiaryContainer = fcd2fe
$onTertiaryContainer = 644569
$tertiaryFixed = fcd2fe
$tertiaryFixedDim = edc5f0
$onTertiaryFixed = 503355
$onTertiaryFixedVariant = 6f4f73
$error = f97386
$errorDim = c44b5f
$onError = 490013
$errorContainer = 871c34
$onErrorContainer = ff97a3
$primaryPaletteKeyColor = 9b697a
$secondaryPaletteKeyColor = 8e6f79
$tertiaryPaletteKeyColor = 8e6b92
$neutralPaletteKeyColor = 7f7476
$neutralVariantPaletteKeyColor = 847378
$errorPaletteKeyColor = c74d61
$primary_paletteKeyColor = 9b697a
$secondary_paletteKeyColor = 8e6f79
$tertiary_paletteKeyColor = 8e6b92
$neutral_paletteKeyColor = 7f7476
$neutral_variant_paletteKeyColor = 847378
$term0 = 353434
$term1 = ff4b8b
$term2 = ffbbb8
$term3 = ffdedf
$term4 = b3a2d5
$term5 = e98fb1
$term6 = ffba93
$term7 = eed1d2
$term8 = b39e9f
$term9 = ff80a4
$term10 = ffd3d0
$term11 = fff1f0
$term12 = dcbc93
$term13 = f8a8c2
$term14 = ffd1c0
$term15 = ffffff
$rosewater = ffedef
$flamingo = fcd9e1
$pink = ffd1e2
$mauve = ffa4d6
$red = fc94b9
$maroon = f3aac0
$peach = ffbcc6
$yellow = ffeded
$green = ffd8c5
$teal = dedcff
$sky = ebd1ff
$sapphire = f2b2f2
$blue = f3a3df
$lavender = feb7e5
$klink = b76eae
$klinkSelection = b66eae
$kvisited = c45d97
$kvisitedSelection = c45d97
$knegative = e84f8a
$knegativeSelection = e74f8a
$kneutral = ff859e
$kneutralSelection = ff859f
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = f6e0e5
$subtext1 = b9a6ab
$subtext0 = 827176
$overlay2 = 726367
$overlay1 = 615457
$overlay0 = 524649
$surface2 = 43383b
$surface1 = 342b2d
$surface0 = 231c1d
$base = 130d0e
$mantle = 130d0e
$crust = 120c0d
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
