$background = 131315
$onBackground = e4e2e4
$surface = 131315
$surfaceDim = 131315
$surfaceBright = 39393b
$surfaceContainerLowest = 0d0e10
$surfaceContainerLow = 1b1b1d
$surfaceContainer = 1f2021
$surfaceContainerHigh = 292a2c
$surfaceContainerHighest = 343537
$onSurface = e4e2e4
$surfaceVariant = 44474d
$onSurfaceVariant = c4c6ce
$outline = 8e9198
$outlineVariant = 44474d
$inverseSurface = e4e2e4
$inverseOnSurface = 303032
$shadow = 000000
$scrim = 000000
$surfaceTint = b5c7e7
$primary = b5c7e7
$primaryDim = c9dbfc
$onPrimary = 1f314a
$primaryContainer = 8496b4
$onPrimaryContainer = 1c2e47
$inversePrimary = 4e5f7b
$primaryFixed = d4e3ff
$primaryFixedDim = b5c7e7
$onPrimaryFixed = 081c34
$onPrimaryFixedVariant = 364862
$secondary = c0c7d5
$secondaryDim = dde2f1
$onSecondary = 2a313c
$secondaryContainer = 414753
$onSecondaryContainer = afb5c3
$secondaryFixed = dde2f1
$secondaryFixedDim = c0c7d5
$onSecondaryFixed = 151c26
$onSecondaryFixedVariant = 414753
$tertiary = e0bcdb
$tertiaryDim = fdd7f8
$onTertiary = 412841
$tertiaryContainer = ac8ba9
$onTertiaryContainer = 3e253e
$tertiaryFixed = fdd7f8
$tertiaryFixedDim = e0bcdb
$onTertiaryFixed = 2a132b
$onTertiaryFixedVariant = 593e58
$error = ffb4ab
$errorDim = ff554a
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryPaletteKeyColor = 667895
$secondaryPaletteKeyColor = 717784
$tertiaryPaletteKeyColor = ac8ba9
$neutralPaletteKeyColor = 777779
$neutralVariantPaletteKeyColor = 74777e
$errorPaletteKeyColor = de3730
$primary_paletteKeyColor = 667895
$secondary_paletteKeyColor = 717784
$tertiary_paletteKeyColor = ac8ba9
$neutral_paletteKeyColor = 777779
$neutral_variant_paletteKeyColor = 74777e
$term0 = 343434
$term1 = 8383ff
$term2 = 44def5
$term3 = ffdcf2
$term4 = 89aed3
$term5 = 99a6ef
$term6 = 92d1f9
$term7 = ccdcd6
$term8 = ac9fa9
$term9 = a29eff
$term10 = 89ecff
$term11 = c9fff3
$term12 = acc4d9
$term13 = b4bbf9
$term14 = b4e1ff
$term15 = ffffff
$rosewater = f4f0fa
$flamingo = e1e0f5
$pink = d5dbff
$mauve = a7bfff
$red = a4aeff
$maroon = b6bbf1
$peach = e0c2f9
$yellow = d0f9f4
$green = bfe5ff
$teal = c6e3ff
$sky = c1deff
$sapphire = 9fcbff
$blue = 94bfff
$lavender = b4cdff
$klink = 518acd
$klinkSelection = 4f8acd
$kvisited = 597cdd
$kvisitedSelection = 567ddd
$knegative = 7179ff
$knegativeSelection = 6f7aff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 00b4fa
$kpositiveSelection = 00b5f9
$text = e4e2e4
$subtext1 = c4c6ce
$subtext0 = 8e9198
$overlay2 = 7c7e84
$overlay1 = 696b70
$overlay0 = 58595e
$surface2 = 47484c
$surface1 = 37373a
$surface0 = 252527
$base = 131315
$mantle = 131315
$crust = 121214
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
