$background = 130d0e
$onBackground = f6e0e5
$surface = 130d0e
$surfaceDim = 130d0e
$surfaceBright = 35292d
$surfaceContainerLowest = 000000
$surfaceContainerLow = 191114
$surfaceContainer = 20171a
$surfaceContainerHigh = 271d20
$surfaceContainerHighest = 2f2226
$onSurface = f6e0e5
$surfaceVariant = 2f2226
$onSurfaceVariant = b9a6ab
$outline = 827176
$outlineVariant = 524448
$inverseSurface = fff8f8
$inverseOnSurface = 5c5355
$shadow = 000000
$scrim = 000000
$surfaceTint = f1b6ca
$primary = f1b6ca
$primaryDim = e2a9bd
$onPrimary = 5d3344
$primaryContainer = 724556
$onPrimaryContainer = ffdae5
$inversePrimary = 805163
$primaryFixed = fdc1d5
$primaryFixedDim = eeb4c8
$onPrimaryFixed = 4f2838
$onPrimaryFixedVariant = 704354
$secondary = e2bdc8
$secondaryDim = d3afba
$onSecondary = 533942
$secondaryContainer = 4e343d
$onSecondaryContainer = dab6c1
$secondaryFixed = ffd9e4
$secondaryFixedDim = f0cbd6
$onSecondaryFixed = 523841
$onSecondaryFixedVariant = 70545d
$tertiary = fedeff
$tertiaryDim = f5cdf9
$onTertiary = 694a6f
$tertiaryContainer = f5cdf9
$onTertiaryContainer = 604266
$tertiaryFixed = f5cdf9
$tertiaryFixedDim = e7bfea
$onTertiaryFixed = 4c2f52
$onTertiaryFixedVariant = 6a4b70
$error = f97386
$errorDim = c44b5f
$onError = 490013
$errorContainer = 871c34
$onErrorContainer = ff97a3
$primaryPaletteKeyColor = 9b697b
$secondaryPaletteKeyColor = 8e6f79
$tertiaryPaletteKeyColor = 8e6c92
$neutralPaletteKeyColor = 7f7477
$neutralVariantPaletteKeyColor = 847378
$errorPaletteKeyColor = c74d61
$primary_paletteKeyColor = 9b697b
$secondary_paletteKeyColor = 8e6f79
$tertiary_paletteKeyColor = 8e6c92
$neutral_paletteKeyColor = 7f7477
$neutral_variant_paletteKeyColor = 847378
$term0 = 353434
$term1 = ff4b8e
$term2 = ffbbb9
$term3 = ffdedf
$term4 = b3a2d5
$term5 = e990b2
$term6 = ffba93
$term7 = eed1d2
$term8 = b39e9f
$term9 = ff80a6
$term10 = ffd3d1
$term11 = fff1f1
$term12 = dcbc93
$term13 = f8a8c3
$term14 = ffd1c0
$term15 = ffffff
$rosewater = ffedf0
$flamingo = fcd9e1
$pink = ffd1e2
$mauve = fea4d7
$red = fb95ba
$maroon = f2aac1
$peach = ffbcc7
$yellow = ffeded
$green = ffd8c5
$teal = dedcff
$sky = ebd1ff
$sapphire = f2b2f2
$blue = f2a3e1
$lavender = feb7e6
$klink = b66eae
$klinkSelection = b66eae
$kvisited = c45d97
$kvisitedSelection = c45d97
$knegative = e74f8b
$knegativeSelection = e74f8a
$kneutral = ff849f
$kneutralSelection = ff859f
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = f6e0e5
$subtext1 = b9a6ab
$subtext0 = 827176
$overlay2 = 726367
$overlay1 = 615457
$overlay0 = 524649
$surface2 = 43383b
$surface1 = 342b2d
$surface0 = 231c1d
$base = 130d0e
$mantle = 130d0e
$crust = 120c0d
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
